# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180422_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='\u4f7f\u7528markdown'),
        ),
    ]
