# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default='', help_text='\u6b63\u6587\u5fc5\u987b\u4e3aMarkDown\u683c\u5f0f', verbose_name='html\u6e32\u67d3\u540e\u7684\u9875\u9762'),
        ),
    ]
