# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180422_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=0, verbose_name='pv'),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=0, verbose_name='uv'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='\u6ce8\uff1a\u6b63\u6587\u53ef\u4ee5\u4f7f\u7528markdown\u7f16\u8f91', verbose_name='\u6b63\u6587\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.TextField(default='', help_text='\u6ce8\uff1a\u6b63\u6587\u53ef\u4ee5\u4f7f\u7528markdown\u7f16\u8f91', verbose_name='html\u6e32\u67d3\u540e\u7684\u9875\u9762'),
        ),
    ]
